package package1;


import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import package1.Display;
import package1.Result;


public class Playquiz_1 extends javax.swing.JFrame {
    private static Object bg;
public static int i=0;
    int m;
     ResultSet rs;
     String radioText;
     String s1;
    public static  int Count=0;
     String s;
ArrayList<Display> displaylist=new ArrayList<Display>();

public void table()
{
    if(i<=m)
    {
       System.out.println(i+"ff"+m);
    
    jlabel2.setText(displaylist.get(i).getQuestion());
     r1.setText(displaylist.get(i).getOption1());
     r2.setText(displaylist.get(i).getOption2());
     r3.setText(displaylist.get(i).getOption3());
     r4.setText(displaylist.get(i).getOption4());
    s1=displaylist.get(i).getCorrect();
     
    }
    else
    {
      Result r=new Result();
        r.setVisible(true);  
        dispose();
    }
    
}
public void groupButton()
{
    ButtonGroup bg=new ButtonGroup();
    bg.add(r1);
    bg.add(r2);
    bg.add(r3);
    bg.add(r4);
    // bg.clearSelection();
}
/*public void groupButton()
{
    if(r1.isSelected())
       {
           radioText=r1.getText();
       }
       
        if(r2.isSelected())
       {
           radioText=r2.getText();
       }
         if(r3.isSelected())
       {
           radioText=r3.getText();
       }
          if(r4.isSelected())
       {
           radioText=r4.getText();
       }
}*/








   
    public Playquiz_1() {
        initComponents();
       groupButton();
      //  bg.clearSelection();
       
        s=Categories.cat;
        System.out.println(s);
           try
{
     //s=Categories.cat;
       // System.out.println(s);
Class.forName("oracle.jdbc.driver.OracleDriver");

    java.sql.Connection con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","NISHTHA123","naina1234");
System.out.println("connected");
String sql="Select * from  QUIZ WHERE CAT='"+s+"'";

    PreparedStatement pst=con.prepareStatement(sql);
    System.out.println("connected");
    
    
     rs=pst.executeQuery();
System.out.println("connected"+"hgvhn");


    while(rs.next())
    {
        m=displaylist.size();
        System.out.println(m+"kk");
        Display d=new Display();
        d.setQuestion(rs.getString("QUESTION"));
        d.setOption1(rs.getString("OP_1"));
        d.setOption2(rs.getString("OP_2"));
        d.setOption3(rs.getString("OP_3"));
        d.setOption4(rs.getString("OP_4"));
       d.setCorrect(rs.getString("CORRECT"));
          displaylist.add(d);
          System.out.println(rs.getString("QUESTION"));
        
        
        
    }   
table();
}
 catch(Exception e)
{
System.out.println(e);
}
           
           
          // Result rd=new Result();
          // rd.setVisible(true);
/*finally{
               
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        r1 = new javax.swing.JRadioButton();
        Next = new javax.swing.JButton();
        r3 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        jlabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 300));
        setMinimumSize(new java.awt.Dimension(700, 500));

        jPanel1.setLayout(null);

        r1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        r1.setText("jRadioButton1");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        jPanel1.add(r1);
        r1.setBounds(60, 140, 560, 40);

        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        jPanel1.add(Next);
        Next.setBounds(490, 370, 110, 40);

        r3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        r3.setText("jRadioButton1");
        jPanel1.add(r3);
        r3.setBounds(60, 260, 560, 40);

        r2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        r2.setText("jRadioButton2");
        jPanel1.add(r2);
        r2.setBounds(60, 200, 560, 40);

        r4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        r4.setText("jRadioButton3");
        jPanel1.add(r4);
        r4.setBounds(60, 320, 560, 40);

        jlabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabel2.setText("jLabel2");
        jPanel1.add(jlabel2);
        jlabel2.setBounds(100, 30, 570, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Q :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 50, 20, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Final.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 680, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
        /*  if(r1.isSelected())
       {
           radioText=r1.getText();
            r2.setSelected(false);
            r3.setSelected(false);
            r4.setSelected(false);
            
          
       }*/
    }//GEN-LAST:event_r1ActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        
        
         if(r1.isSelected())
       {
           radioText=r1.getText();
            r2.setSelected(false);
            r3.setSelected(false);
            r4.setSelected(false);
       }
        else  if(r2.isSelected())
       {
           radioText=r2.getText();
            r1.setSelected(false);
            r3.setSelected(false);
            r4.setSelected(false);
       }
        else   if(r3.isSelected())
       {
           radioText=r3.getText();
            r1.setSelected(false);
            r3.setSelected(false);
            r4.setSelected(false);
       }
           else if(r4.isSelected())
       {
           radioText=r4.getText();
            r1.setSelected(false);
            r2.setSelected(false);
            r3.setSelected(false);
       }
         else
           {
               radioText="  ";
           }
            
            if(radioText.equals(s1))
            {
                Count++;
                System.out.println(Count);
                
            }
            i++;
            table();
            //Result rd=new Result();
        //  rd.setVisible(true);
    }//GEN-LAST:event_NextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Playquiz_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Playquiz_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Playquiz_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Playquiz_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//bg.clearSelection();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Playquiz_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Next;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    // End of variables declaration//GEN-END:variables

  
}
