/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package package1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Signin2 extends javax.swing.JFrame {
String password;
String name;
String username;
    /**
     * Creates new form Signin2
     */
    public Signin2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernametextfield = new javax.swing.JTextField();
        Nametextfield = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Passwordtextfield = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 300));
        setMinimumSize(new java.awt.Dimension(600, 400));

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText(" Name  :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 140, 120, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Username  :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 200, 150, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Password  :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 260, 150, 50);

        usernametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametextfieldActionPerformed(evt);
            }
        });
        jPanel1.add(usernametextfield);
        usernametextfield.setBounds(410, 200, 160, 40);
        jPanel1.add(Nametextfield);
        Nametextfield.setBounds(410, 130, 160, 40);

        Submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Submit.setText("Register");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit);
        Submit.setBounds(520, 330, 140, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Enter your Details");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 70, 450, 40);

        Passwordtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordtextfieldActionPerformed(evt);
            }
        });
        jPanel1.add(Passwordtextfield);
        Passwordtextfield.setBounds(410, 260, 160, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel4.setText("QUIZ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 10, 100, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Final.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 720, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        password=Passwordtextfield.getText();
        name=Nametextfield.getText();
        username=usernametextfield.getText();
    //    is_Valid_Password(password);
    if(name.trim().isEmpty())
    {
    JOptionPane.showMessageDialog(Signin2.this, "name is empty");
    }
    
if(is_Valid_Password(password))
{
    table();
    //JOptionPane.showMessageDialog(Signin2.this, "");
   // System.out.println(password);
     Categories cg=new Categories();
        cg.setVisible(true);
        dispose();
   
}
else{
         invalid_password(password);
}
    }//GEN-LAST:event_SubmitActionPerformed

    
      public void invalid_password(String password)
  {
  int i2=8;  
			    int s1=password.length();  
				
			 if(s1<i2)
			   {
                JOptionPane.showMessageDialog(null,"A password must not have atleast eight(8) character \n Click OK  and try again .2","Wronge Pass",JOptionPane.ERROR_MESSAGE);
				//System.out.println("Password is not Valid ="+password);
			   }
                         else  
			 {
			
                             String s2=password;
			   //System.out.println(s2);
				 if(s2.matches("[0-9]")&&s2.length()>8)
			        {
				       JOptionPane.showMessageDialog(null," A password only  consist of digit&& doesnot have any  character.It always conist of atleat Two character \n Click OK  and try again .2","Wronge Pass",JOptionPane.ERROR_MESSAGE);
				      // System.out.println("Password is not Valid ="+password);
			        } 
		        else 
			        {
				       JOptionPane.showMessageDialog(null," A password doesnot consist of any number or digit.It contain atleast two number \n Click OK  and try again .2","Wronge Pass",JOptionPane.ERROR_MESSAGE);
				     //   System.out.println("Password is not Valid ="+password);
			        }
                         }
  
  }
    
    
    
     public static boolean is_Valid_Password(String password)
    {
       int  PASSWORD_Length=8;
       if(password.length()<PASSWORD_Length)
		{
			return false;
		}
      else
		{
		   int charCount=0 ;
		   int  numCount=0;
		   for(int i=0;i<password.length();i++)
		     {
			    char ch=password.charAt(i);
				
				if(is_Numeric(ch))
				 {
				   numCount++;
				  }
	            else if(is_Letter(ch))
				 {
				   charCount++;
				  }
				else 
				 {
				   return false;
				  }
			   }
				return (charCount>=2&&numCount>=2);
		}
	}	
		
  public static boolean is_Letter(char ch)
    {
       ch=Character.toUpperCase(ch);
        return (ch>='A'&&ch<='Z');
	}
 public static boolean is_Numeric(char ch)
    {
		return (ch>='0'&&ch<='9');
	}
 
 
 // SignIn sig=new SignIn();
      //  sig.setVisible(true);
       // dispose();
        
    private void PasswordtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordtextfieldActionPerformed

    private void usernametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametextfieldActionPerformed

    public void table()
    {
         try
            {
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","NISHTHA123","naina1234");
             System.out.println("connected");
             String sql="INSERT INTO SIGNIN(NAME,USERNAME,PASSWORD)VALUES(?,?,?)";

                PreparedStatement pst=con.prepareStatement(sql);
                System.out.println("connected");

                pst.setString(1,username);
                pst.setString(2,name);
                pst.setString(3,password);
                System.out.println(username+name+password);
                
                 int rs=pst.executeUpdate();
    if(rs>0)
    {
        System.out.println("insert");
    }
    else
    {
        
    }
            }
         catch(Exception e)
         {
             
         }
    

    
}
    
    /**
     * @param args the command line arguments
     */
         
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signin2().setVisible(true);
                 //SignIn sig=new SignIn();
       // sig.setVisible(true);
                //dispose();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nametextfield;
    private javax.swing.JPasswordField Passwordtextfield;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField usernametextfield;
    // End of variables declaration//GEN-END:variables
}
